[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:standalone"

[start.healthcheck]
command = "curl -f http://$(hostname):3000/api/health || exit 1"
interval = "10s"
timeout = "3s"
startPeriod = "30s"
retries = 3